export const REQUEST_CONTENT_LIST = 'REQUEST_CONTENT_LIST'
export const GET_CONTENT_LIST = 'GET_CONTENT_LIST'
export const GET_CONTENT_LIST_LENGTH = 'GET_CONTENT_LIST_LENGTH'
export const GET_CONTENT_LIST_FAILURE = 'GET_CONTENT_LIST_FAILURE'

export const GET_ARTICLE = 'GET_ARTICLE'
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE'
export const CLEAR_ARTICLE = 'CLEAR_ARTICLE'

export const POST_ARTICLE = 'POST_ARTICLE'
export const POST_ARTICLE_FAILURE = 'POST_ARTICLE_FAILURE'
